### PR TITLE
Upgrade lodash

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by phated** [comment]
Ref https://github.com/gulpjs/undertaker/pull/56#issuecomment-182011145

**Comment by TrySound** [comment]
Let's merge this, caz there are changes. And split lodash in the next pr

**Comment by phated** [comment]
Sorry, missed that.

**Comment by phated** [comment]
I'm not going to cut a release with these changes though, doesn't seem to make sense.

**Pull request merged**
